package com.uberj.ditsanddahs;

import com.google.common.collect.ImmutableList;
import com.uberj.ditsanddahs.keyboards.Keys;

import static com.uberj.ditsanddahs.keyboards.KeyConfig.l;
import static com.uberj.ditsanddahs.keyboards.KeyConfig.p;
import static com.uberj.ditsanddahs.keyboards.KeyConfig.s;

public class CommonWords {
    public static final ImmutableList<String> sequence = new ImmutableList.Builder<String>()
            .add("R")
            .add("TU")
            .add("RTU")
            .add("TNX")
            .add("NAME")
            .add("RST")
            .add("CQ")
            .add("AGN")
            .add("ANT")
            .add("DX")
            .add("ES")
            .add("FB")
            .add("GA")
            .add("GE")
            .add("HI")
            .add("HR")
            .add("HW")
            .add("NR")
            .add("OM")
            .add("PSE")
            .add("PWR")
            .add("WX")
            .add("73")
            .add("QRL")
            .add("QRM")
            .add("QRN")
            .add("QRQ")
            .add("QRS")
            .add("QRZ")
            .add("QTH")
            .add("QSB")
            .add("QSY")
            .add("AR")
            .add("KN")
            .add("BK")
            .add("AS")
            .add("SK")
            .add("I")
            .add("AND")
            .add("THE")
            .add("YOU")
            .add("THAT")
            .add("A")
            .add("TO")
            .add("KNOW")
            .add("OF")
            .add("IT")
            .add("YEAH")
            .add("IN")
            .add("THEY")
            .add("DO")
            .add("SO")
            .add("BUT")
            .add("IS")
            .add("LIKE")
            .add("HAVE")
            .add("WAS")
            .add("WE")
            .add("ITS")
            .add("JUST")
            .add("ON")
            .add("OR")
            .add("NOT")
            .add("THINK")
            .add("FOR")
            .add("WELL")
            .add("WHAT")
            .add("ABOUT")
            .add("ALL")
            .add("THATS")
            .add("OH")
            .add("REALLY")
            .add("ONE")
            .add("ARE")
            .add("RIGHT")
            .add("UH")
            .add("THEM")
            .add("AT")
            .add("THERE")
            .add("MY")
            .add("MEAN")
            .add("DONT")
            .add("NOT")
            .add("WITH")
            .add("IF")
            .add("WHEN")
            .add("CAN")
            .add("BE")
            .add("AS")
            .add("OUT")
            .add("KIND")
            .add("BECAUSE")
            .add("PEOPLE")
            .add("GO")
            .add("GOT")
            .add("THIS")
            .add("SOME")
            .add("IM")
            .add("WOULD")
            .add("THINGS")
            .add("NOW")
            .add("LOT")
            .add("HAD")
            .add("HOW")
            .add("GOOD")
            .add("GET")
            .add("SEE")
            .add("FROM")
            .add("HE")
            .add("ME")
            .add("DONT")
            .add("THEIR")
            .add("MORE")
            .add("ITS")
            .add("THATS")
            .add("TOO")
            .add("OKAY")
            .add("VERY")
            .add("UP")
            .add("BEEN")
            .add("GUESS")
            .add("TIME")
            .add("GOING")
            .add("INTO")
            .add("THOSE")
            .add("HERE")
            .add("DID")
            .add("WORK")
            .add("OTHER")
            .add("AND")
            .add("IVE")
            .add("THINGS")
            .add("EVEN")
            .add("OUR")
            .add("ANY")
            .add("IM")
            .build();

    public static Keys keyboard() {
        return () -> ImmutableList.of(
                ImmutableList.of(l("1"), l("2"), l("3"), l("4"), l("5"), l("6"), l("7"), l("8"), l("9"), l("0"), l("/"), p("=")),
                ImmutableList.of(s(), l("Q"), l("W"), l("e"), l("r"), l("T"), l("Y"), l("U"), l("I"), l("O"), l("P"), s(1), s()),
                ImmutableList.of(s(1), l("A"), l("S"), l("D"), l("F"), l("G"), l("H"), l("J"), l("K"), l("L"), l("?"), s(1)),
                ImmutableList.of(s(), l(","), l("Z"), l("X"), l("C"), l("V"), l("B"), l("N"), l("M"), l("."), s(2), s())
        );
    }

}
