package com.example.uberj.test1;

import com.google.common.collect.ImmutableList;

public class KochLetterSequence {
    public static final ImmutableList<String> sequence = new ImmutableList.Builder<String>()
            .add("K")
            .add("M")
            .add("U")
            .add("R")
            .add("E")
            .add("S")
            .add("N")
            .add("A")
            .add("P")
            .add("T")
            .add("L")
            .add("W")
            .add("I")
            .add(".")
            .add("J")
            .add("Z")
            .add("BT")
            .add("F")
            .add("O")
            .add("Y")
            .add(",")
            .add("V")
            .add("G")
            .add("5")
            .add("/")
            .add("Q")
            .add("9")
            .add("2")
            .add("H")
            .add("3")
            .add("8")
            .add("B")
            .add("?")
            .add("4")
            .add("7")
            .add("C")
            .add("1")
            .add("D")
            .add("6")
            .add("0")
            .add("X")
            .build();
}
