package com.uberj.pocketmorsepro;

import com.google.common.collect.ImmutableList;
import com.uberj.pocketmorsepro.keyboards.Keys;

import static com.uberj.pocketmorsepro.keyboards.KeyConfig.l;
import static com.uberj.pocketmorsepro.keyboards.KeyConfig.p;
import static com.uberj.pocketmorsepro.keyboards.KeyConfig.s;

public class CommonWords {
    public static final ImmutableList<String> sequence = new ImmutableList.Builder<String>()
            .add("i")
            .add("and")
            .add("the")
            .add("you")
            .add("that")
            .add("a")
            .add("to")
            .add("know")
            .add("of")
            .add("it")
            .add("yeah")
            .add("in")
            .add("they")
            .add("do")
            .add("so")
            .add("but")
            .add("is")
            .add("like")
            .add("have")
            .add("was")
            .add("we")
            .add("its")
            .add("just")
            .add("on")
            .add("or")
            .add("not")
            .add("think")
            .add("for")
            .add("well")
            .add("what")
            .add("about")
            .add("all")
            .add("thats")
            .add("oh")
            .add("really")
            .add("one")
            .add("are")
            .add("right")
            .add("uh")
            .add("them")
            .add("at")
            .add("there")
            .add("my")
            .add("mean")
            .add("dont")
            .add("not")
            .add("with")
            .add("if")
            .add("when")
            .add("can")
            .add("be")
            .add("as")
            .add("out")
            .add("kind")
            .add("because")
            .add("people")
            .add("go")
            .add("got")
            .add("this")
            .add("some")
            .add("im")
            .add("would")
            .add("things")
            .add("now")
            .add("lot")
            .add("had")
            .add("how")
            .add("good")
            .add("get")
            .add("see")
            .add("from")
            .add("he")
            .add("me")
            .add("dont")
            .add("their")
            .add("more")
            .add("its")
            .add("thats")
            .add("too")
            .add("okay")
            .add("very")
            .add("up")
            .add("been")
            .add("guess")
            .add("time")
            .add("going")
            .add("into")
            .add("those")
            .add("here")
            .add("did")
            .add("work")
            .add("other")
            .add("and")
            .add("ive")
            .add("things")
            .add("even")
            .add("our")
            .add("any")
            .add("im")
            .add("r")
            .add("tu")
            .add("rtu")
            .add("tnx")
            .add("name")
            .add("rst")
            .add("cq")
            .add("agn")
            .add("ant")
            .add("dx")
            .add("es")
            .add("fb")
            .add("ga")
            .add("ge")
            .add("hi")
            .add("hr")
            .add("hw")
            .add("nr")
            .add("om")
            .add("pse")
            .add("pwr")
            .add("wx")
            .add("73")
            .add("qrl")
            .add("qrm")
            .add("qrn")
            .add("qrq")
            .add("qrs")
            .add("qrz")
            .add("qth")
            .add("qsb")
            .add("qsy")
            .add("ar")
            .add("kn")
            .add("bk")
            .add("as")
            .add("sk")
            .build();

    public static Keys keyboard() {
        return () -> ImmutableList.of(
                ImmutableList.of(l("1"), l("2"), l("3"), l("4"), l("5"), l("6"), l("7"), l("8"), l("9"), l("0"), l("/"), p("=")),
                ImmutableList.of(s(), l("Q"), l("W"), l("e"), l("r"), l("T"), l("Y"), l("U"), l("I"), l("O"), l("P"), s(1), s()),
                ImmutableList.of(s(1), l("A"), l("S"), l("D"), l("F"), l("G"), l("H"), l("J"), l("K"), l("L"), l("?"), s(1)),
                ImmutableList.of(s(), l(","), l("Z"), l("X"), l("C"), l("V"), l("B"), l("N"), l("M"), l("."), s(2), s())
        );
    }

}
